### PR TITLE
Remove TODO and add basic usage instructions

### PR DESCRIPTION
**Pull request by foobar0815**
This change is [Reviewable](https://reviewable.io/reviews/foobar0815/guenther/58)

### CODE REVIEW

**Comment by marius** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[README.md, line 19 [r1]](https://reviewable.io:443/reviews/foobar0815/guenther/58#-KEmSxnbAc9M9P17_0iA:-KEmSxncpN9px6ix1AIw:1346427731) ([raw file](https://github.com/foobar0815/guenther/blob/7221651c9895c2ad079e552d7170bd553b81a87e/README.md#L19)):_
How about removing the ./? It does not seem common in usage descriptions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/foobar0815/guenther/58)_

**Comment by foobar0815** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[README.md, line 19 [r1]](https://reviewable.io:443/reviews/foobar0815/guenther/58#-KEmSxnbAc9M9P17_0iA:-KEobLM1a72zzfh98dD6:510824073) ([raw file](https://github.com/foobar0815/guenther/blob/7221651c9895c2ad079e552d7170bd553b81a87e/README.md#L19)):_
Wasn't quite sure about this myself... what do you think of using a stylized prompt in front of the command?

$ guenther

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/foobar0815/guenther/58)_

**Comment by marius** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[README.md, line 19 [r1]](https://reviewable.io:443/reviews/foobar0815/guenther/58#-KEmSxnbAc9M9P17_0iA:-KEp2_xzfI5j4b-WbX8Y:-1504763431) ([raw file](https://github.com/foobar0815/guenther/blob/7221651c9895c2ad079e552d7170bd553b81a87e/README.md#L19)):_
Good idea.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/foobar0815/guenther/58)_

**Comment by marius** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/foobar0815/guenther/58#-:-KEwDkJfRVIEXc3pTYf8:1417088721)_

**Pull request merged**
