### PR TITLE
Support for multilingual quizdata

### PR DESCRIPTION
**Pull request by foobar0815**
This change is [Reviewable](https://reviewable.io/reviews/foobar0815/guenther/31)

### CODE REVIEW

**Comment by marius** [comment]
Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions.

---

_[quizbot.rb, line 119 [r1]](https://reviewable.io:443/reviews/foobar0815/guenther/31#-KDAYZ-xfylF-itCSGXH:-KDAYZ-y_-a84mFGaeoX:-1007835335) ([raw file](https://github.com/foobar0815/guenther/blob/17e01e6660c7887d9f59252212512f7de871eebe/quizbot.rb#L119)):_
No need to call split twice.

---

_[quizbot.rb, line 147 [r1]](https://reviewable.io:443/reviews/foobar0815/guenther/31#-KDAZ26E95HBIzUNd4gx:-KDAZ26E95HBIzUNd4gy:-465060648) ([raw file](https://github.com/foobar0815/guenther/blob/17e01e6660c7887d9f59252212512f7de871eebe/quizbot.rb#L147)):_
I think l should be q here, as the variable references a single question. Maybe we should change it to "question" if it is confusing.

---

_[quizbot.rb, line 152 [r1]](https://reviewable.io:443/reviews/foobar0815/guenther/31#-KDAZIWkfI_r1TiuFAdf:-KDAZIWlG91X83hchlK7:-1475836859) ([raw file](https://github.com/foobar0815/guenther/blob/17e01e6660c7887d9f59252212512f7de871eebe/quizbot.rb#L152)):_
As we are overwriting the questions variable with a subset of itself we should probably use select!().
questions.select! { old body here } unless @config.category == 'all'

---

_[quizbot.rb, line 200 [r1]](https://reviewable.io:443/reviews/foobar0815/guenther/31#-KDAZyoj4cxjL3-Wmnta:-KDAZyok3tBZk4mboSNO:-1036239019) ([raw file](https://github.com/foobar0815/guenther/blob/17e01e6660c7887d9f59252212512f7de871eebe/quizbot.rb#L200)):_
Same variable naming problem as above.

---

_[quizbot.rb, line 216 [r1]](https://reviewable.io:443/reviews/foobar0815/guenther/31#-KDA_CGYdw3m2BMtUmYA:-KDA_CGYdw3m2BMtUmYB:-1432499915) ([raw file](https://github.com/foobar0815/guenther/blob/17e01e6660c7887d9f59252212512f7de871eebe/quizbot.rb#L216)):_
I think this line can be folded into the next line.

---

_[quizbot.rb, line 312 [r1]](https://reviewable.io:443/reviews/foobar0815/guenther/31#-KDA_TN4Qc_9FldXhytV:-KDA_TN4Qc_9FldXhytW:-445621770) ([raw file](https://github.com/foobar0815/guenther/blob/17e01e6660c7887d9f59252212512f7de871eebe/quizbot.rb#L312)):_
in language #{value}

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/foobar0815/guenther/31)_

**Comment by marius** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/foobar0815/guenther/31)_

**Comment by foobar0815** [comment]
Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions.

---

_[quizbot.rb, line 119 [r1]](https://reviewable.io:443/reviews/foobar0815/guenther/31#-KDAYZ-xfylF-itCSGXH:-KDCltBO6VWJOwZFd0KH:334801042) ([raw file](https://github.com/foobar0815/guenther/blob/17e01e6660c7887d9f59252212512f7de871eebe/quizbot.rb#L119)):_
Ok, but the variable naming looks inadequate now. Should we have some "naming convention" for split strings (filenameSplit, fnSplit, fn,...)?

---

_[quizbot.rb, line 147 [r1]](https://reviewable.io:443/reviews/foobar0815/guenther/31#-KDAZ26E95HBIzUNd4gx:-KDCn7o7tG9dAMqK9Z6j:-499146009) ([raw file](https://github.com/foobar0815/guenther/blob/17e01e6660c7887d9f59252212512f7de871eebe/quizbot.rb#L147)):_
Done.

---

_[quizbot.rb, line 152 [r1]](https://reviewable.io:443/reviews/foobar0815/guenther/31#-KDAZIWkfI_r1TiuFAdf:-KDCkmIph0kzBnUwH4en:-1989520445) ([raw file](https://github.com/foobar0815/guenther/blob/17e01e6660c7887d9f59252212512f7de871eebe/quizbot.rb#L152)):_
I used a slightly different syntax to keep rubocop from complaining about a too long line.

---

_[quizbot.rb, line 200 [r1]](https://reviewable.io:443/reviews/foobar0815/guenther/31#-KDAZyoj4cxjL3-Wmnta:-KDCn0bpglFUsW7Z81FE:-499146009) ([raw file](https://github.com/foobar0815/guenther/blob/17e01e6660c7887d9f59252212512f7de871eebe/quizbot.rb#L200)):_
Done.

---

_[quizbot.rb, line 216 [r1]](https://reviewable.io:443/reviews/foobar0815/guenther/31#-KDA_CGYdw3m2BMtUmYA:-KDCn2Bpg8ah6qcWeIyh:-499146009) ([raw file](https://github.com/foobar0815/guenther/blob/17e01e6660c7887d9f59252212512f7de871eebe/quizbot.rb#L216)):_
Done.

---

_[quizbot.rb, line 312 [r1]](https://reviewable.io:443/reviews/foobar0815/guenther/31#-KDA_TN4Qc_9FldXhytV:-KDCmbKCq-aaJOwrMlA9:-1501742126) ([raw file](https://github.com/foobar0815/guenther/blob/17e01e6660c7887d9f59252212512f7de871eebe/quizbot.rb#L312)):_
It would be nice to say "in german language", but since we only have the language code... ack&done.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/foobar0815/guenther/31)_

**Comment by foobar0815** [comment]
Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions.

---

_[quizbot.rb, line 119 [r1]](https://reviewable.io:443/reviews/foobar0815/guenther/31#-KDAYZ-xfylF-itCSGXH:-KDCqZtEWiiITrsS0QT-:-575669254) ([raw file](https://github.com/foobar0815/guenther/blob/17e01e6660c7887d9f59252212512f7de871eebe/quizbot.rb#L119)):_
Rubocop recommends snake_case for variable names.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/foobar0815/guenther/31)_

**Comment by marius** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

_[quizbot.rb, line 119 [r1]](https://reviewable.io:443/reviews/foobar0815/guenther/31#-KDAYZ-xfylF-itCSGXH:-KDDHn0yUXY_lZnHJ_uS:-1749736863) ([raw file](https://github.com/foobar0815/guenther/blob/17e01e6660c7887d9f59252212512f7de871eebe/quizbot.rb#L119)):_
How about filename_split? Actually, you don't need to ask for length at all, Ruby supports indexing arrays from the back.
language = filename.split('.')[-2] or so, please test.

---

_[quizbot.rb, line 152 [r1]](https://reviewable.io:443/reviews/foobar0815/guenther/31#-KDAZIWkfI_r1TiuFAdf:-KDDILa5-Ob1fF5bQCFd:-579475681) ([raw file](https://github.com/foobar0815/guenther/blob/17e01e6660c7887d9f59252212512f7de871eebe/quizbot.rb#L152)):_
Please don't assign the result of questions.select! to questions, the return value of select! is nil when it didn't change anything afaik.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/foobar0815/guenther/31)_

**Comment by marius** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/foobar0815/guenther/31#-:-KDDSW-4DEnQZe53-KMF:1417088721)_

**Pull request merged**
